Repository playlegend/WorldEditLab, pull requests merged in 2021-04, with the labels that each got.

#178 Upload Limit
  README.md
  assets/scripts/schematic.js
  package.json
  src/app.ts
Labels: status: approved, type: docs, type: feature

#179 make upload limit changeable
  .github/workflows/build.yml
  README.md
  assets/scripts/schematic.js
  package.json
  src/app.ts
  yarn.lock
Labels: dependencies, status: approved, type: feature

#181 Fix card style issue
  assets/scripts/collection.js
  assets/styles/components/card.css
  package.json
Labels: scope: frontend, status: approved, type: bugfix
